version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=operacao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Z3ld4100%
    ports:
      - "5431:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
