# Generated by Django 3.2.6 on 2021-11-25 01:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0005_auto_20211031_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('size', models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], default='', max_length=2, verbose_name='Tamanho')),
                ('size_number', models.CharField(default='0', max_length=2, verbose_name='Tamanho por número')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='produto.product')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
