# Generated by Django 3.2.6 on 2021-11-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='size',
            field=models.CharField(blank=True, choices=[('1', 'P'), ('2', 'M'), ('3', 'G'), ('4', 'GG')], default='', max_length=2, verbose_name='Tamanho'),
        ),
    ]
