# Generated by Django 3.2.6 on 2021-12-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_estoque_size_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='size_number',
        ),
    ]
