# Generated by Django 3.2.6 on 2021-08-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='gereno',
        ),
        migrations.AddField(
            model_name='peca',
            name='gereno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
