# Generated by Django 3.2.6 on 2021-11-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_user_id_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
