# Generated by Django 3.2.6 on 2021-12-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211125_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frete'),
        ),
    ]
